# Generated by Django 5.2 on 2025-05-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productimage_productoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.PositiveIntegerField(default=0, help_text='Peso base en gramos'),
        ),
        migrations.AddField(
            model_name='productoption',
            name='additional_weight',
            field=models.IntegerField(default=0, help_text='Incremento (+/-) de peso en gramos'),
        ),
    ]
