# Generated by Django 5.2 on 2025-05-19 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_products_total_price_order_shipping_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products_total_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_weight',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product_unit_price',
        ),
    ]
